### ISSUE TITLE
Recommended procedure for feature discretization

### ISSUE THREAD

**Issue by abhishek-ghose** [aia-uclouvain/pydl8.5#3]
Hi,

I am beginning to try out the DL8.5 algorithm. Since it only operates over 0-1 features, continuous features probably need to binned and be represented as dense one-hot vector _outside the library_. Is this correct? If so, is there a recommended feature binning procedure that is known to work well with the technique?

Thanks

**Comment by aglingael** [comment]
In case it could help someone, the continuous features should be binarized outside the library. For this, any approach returning a 0/1 numpy 2d matrix is fine. You could use for instance the [OneHotEncoder](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html#sklearn-preprocessing-onehotencoder) class of the Scikit-learn preprocessing package.
