### ISSUE TITLE
How does dl8.5 work with more than 2 classes?

### ISSUE THREAD

**Issue by gauthsvenkat** [aia-uclouvain/pydl8.5#7]
Hi,

I'd love to use pydl8.5 with one of my projects. However, it is not immediately obvious how to binarize the dataset or how to use the decision trees for more than 2 classes. Am I missing something or is it not possible to use dl8.5 for more than 2 classes?

**Comment by gauthsvenkat** [comment]
Nice, so I don't have to binarize manually? Pydl8.5 will handle it on its own?

**Comment by aglingael** [comment]
You have to binarize your data before running PyDL8.5. I described you in the first paragraph of my answer, how you can do this.
